# Generated by Django 4.0.1 on 2022-03-11 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_managers_book_count_book_price_book_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('HOME DIZAYN', 'home dizayn'), ('LIRIKA', 'Lirika')], default='Lirika', max_length=250),
        ),
        migrations.AlterField(
            model_name='discount',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 11, 52, 15, 690166)),
        ),
    ]
